// ─── Timeline entry types ─────────────────────────────────────────────────────
//
// Every orchestrator invocation produces one groupId. All entries produced by
// that invocation share that groupId to support causal inspection and replay.
//
// id vs correlationId:
//   id            — unique event id, auto-generated by timelineStore.append()
//   correlationId — shared by an execution.call and its matching execution.result
//                   / execution.skipped / execution.simulated

import type { PlanStep } from '@/types/workspace'

/** Structured reason for a skipped execution entry. */
export type SkipReason =
  | 'no_sandbox'          // no active sandbox configured
  | 'replay_simulation'   // running in replay/simulate mode
  | 'validation_failed'   // params failed schema validation
  | 'unsupported'         // primitive threw an error / not implemented

export type ReviewDecision = 'approved' | 'rejected'

export type TimelineEntry =
  /** The orchestrator's reasoning plan for this invocation */
  | {
      kind: 'plan'
      groupId: string
      id: string
      ts: string
      steps: PlanStep[]
    }
  /** The orchestrator intends to call an execution primitive */
  | {
      kind: 'execution.call'
      groupId: string
      id: string
      ts: string
      /** Correlation key — shared with the matching result/skipped entry. */
      correlationId: string
      method: string
      params: unknown
    }
  /** Execution is awaiting human approval before dispatch */
  | {
      kind: 'execution.pending_review'
      groupId: string
      id: string
      ts: string
      correlationId: string
      method: string
      params: unknown
      risk_level: 'low' | 'medium' | 'high'
      reversible: boolean
      side_effect: string
    }
  /** Execution primitive returned a result */
  | {
      kind: 'execution.result'
      groupId: string
      id: string
      ts: string
      /** Links back to the execution.call entry. */
      correlationId: string
      /** Method name preserved for readability — avoids requiring a call lookup. */
      method: string
      result: unknown
      /** Resolved semantic entities touched by this execution result. */
      entityIds?: string[]
    }
  /** Execution was explicitly rejected by the reviewer */
  | {
      kind: 'execution.rejected'
      groupId: string
      id: string
      ts: string
      correlationId: string
      method: string
      params: unknown
      reason: string
      decision: ReviewDecision
    }
  /** Execution was skipped */
  | {
      kind: 'execution.skipped'
      groupId: string
      id: string
      ts: string
      /** Links back to the execution.call entry. */
      correlationId: string
      method: string
      params: unknown
      reason: SkipReason
      /** Optional human-readable detail (e.g. error message). */
      message?: string
    }
  /**
   * Execution was SIMULATED during replay (safe stub — no real side effect).
   * Carries the original method + params so the timeline stays semantically complete.
   */
  | {
      kind: 'execution.simulated'
      groupId: string
      id: string
      ts: string
      /** Links back to the original execution.call entry. */
      correlationId: string
      method: string
      params: unknown
    }
  /** A UI primitive was dispatched to the workspace */
  | {
      kind: 'ui'
      groupId: string
      id: string
      ts: string
      method: string
      params: unknown
    }
